/*
 * This file was generated by the Gradle "init" task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */



plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
     id("org.panteleyev.jpackageplugin") version "1.7.3"
     id("com.gradleup.shadow") version "8.3.9"
}


javafx {
    version = "21"
    modules("javafx.controls", "javafx.fxml")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    //implementation("com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:9.0.0-beta17")

    implementation("org.openjfx:javafx-controls:21")
    implementation("org.openjfx:javafx-fxml:21")
}



// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "file2image.App"
}


var version = "1.0"
var winver = "1.0.0"

tasks.jpackage {
    dependsOn("build", "shadowJar")

    input = layout.buildDirectory.dir("builtJars")
    destination = layout.buildDirectory.dir("builtDist")
    appVersion = winver

    appName = "File2Img"
    vendor = "_FN10_"

    type = org.panteleyev.jpackage.ImageType.APP_IMAGE

    mainJar = "File2Img-$version-all.jar"
    mainClass = "file2image.App"

    windows {
        //type = org.panteleyev.jpackage.ImageType.EXE
        //winConsole = true
    }

    linux {
        //type = org.panteleyev.jpackage.ImageType.DEB
        linuxPackageName = "File2Img"
        linuxShortcut = true
    }
}

tasks.shadowJar {
    archiveBaseName.set("File2Img")
    archiveVersion.set(version)
    destinationDirectory.set(layout.buildDirectory.dir("builtJars"))
}